#!/bin/bash
if [ -n "$DATA_DIR" ]; then
  :
else
  if [ -z "$XDG_DATA_HOME" ]; then
    DATA_DIR=~/.local/share/python-clang
  else
    DATA_DIR=$XDG_DATA_HOME/python-clang
  fi
fi

if [ ! -d "$DATA_DIR" ]; then
  mkdir -p "$DATA_DIR"
fi

if [ -n "$DATA_DIR" ]; then
  DATA_DIR=$(cd "$DATA_DIR" && pwd)
fi

cd /usr/share/python-clang || exit

DATA_DIR=$DATA_DIR /usr/share/python-clang/.venv/bin/python /usr/share/python-clang/clang.py